### ISSUE TITLE
migrations does not work

### ISSUE THREAD

**Issue by MohammadMQ** [Apress/blazor-revealed#1]
Trying to run: "_dotnet-ef database update -v_"  or add own migrations to _PizzaPlace070.Server_ project results in following error:

C:\...\source\repos\BlazorRevealed\Application\PizzaPlace070.Server>dotnet-ef database update -v
Using project 'C:\...\source\repos\BlazorRevealed\Application\PizzaPlace070.Server\PizzaPlace070.Server.csproj'.
Using startup project 'C:\...\source\repos\BlazorRevealed\Application\PizzaPlace070.Server\PizzaPlace070.Server.csproj'.
Writing 'C:\...\source\repos\BlazorRevealed\Application\PizzaPlace070.Server\obj\PizzaPlace070.Server.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\...\AppData\Local\Temp\tmpD6C9.tmp /verbosity:quiet /nologo C:\...\source\repos\BlazorRevealed\Application\PizzaPlace070.Server\PizzaPlace070.Server.csproj
Writing 'C:\...\source\repos\BlazorRevealed\Application\PizzaPlace070.Server\obj\PizzaPlace070.Server.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\...\AppData\Local\Temp\tmpDDCF.tmp /verbosity:quiet /nologo C:\...\source\repos\BlazorRevealed\Application\PizzaPlace070.Server\PizzaPlace070.Server.csproj
dotnet build C:\...\source\repos\BlazorRevealed\Application\PizzaPlace070.Server\PizzaPlace070.Server.csproj /verbosity:quiet /nologo
C:\...\.nuget\packages\microsoft.aspnetcore.blazor.build\0.7.0\targets\RazorCompilation.targets(236,5): error : rzc discover exited with code 1. [C:\...\source\repos\BlazorRevealed\Application\PizzaPlace070.Extensions.Validation\PizzaPlace070.Extensions.Validation.csproj]

Build FAILED.

C:\...\.nuget\packages\microsoft.aspnetcore.blazor.build\0.7.0\targets\RazorCompilation.targets(236,5): error : rzc discover exited with code 1. [C:\...\source\repos\BlazorRevealed\Application\PizzaPlace070.Extensions.Validation\PizzaPlace070.Extensions.Validation.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:02.43
Microsoft.EntityFrameworkCore.Tools.CommandException: Build failed.
   at Microsoft.EntityFrameworkCore.Tools.Project.Build()
   at Microsoft.EntityFrameworkCore.Tools.RootCommand.Execute()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
Build failed.

I'm using the project code as is inside Visual Studio 2017

**Comment by mohammadmirza** [comment]
Found a way to make it work, do the following

-  add <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.1.1" />
-  add<PackageReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0" />
- inside your SQL Server create an empty database: PizzaDb
- edit the connection string to point to PizzaDb:     "PizzaDb": "Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=PizzaDb;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False"
- Inside command prompt go to project: PizzaPlace070.Server and run following command: 
_dotnet ef database update -v_

**Comment by MohammadMQ** [comment]
Found a way to make it work, do the following

add "Microsoft.EntityFrameworkCore.Design" Version="2.1.1"
add "Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0"
inside your SQL Server create an empty database: PizzaDb
edit the connection string to point to PizzaDb:
Inside command prompt go to project: PizzaPlace070.Server and run following command:
dotnet ef database update -v
